---

- name: Install requirements
  apt: name={{item}}
  with_items:
      - apt-transport-https
      - ca-certificates
      - python-pip

- name: Upgrade pip
  pip: name=pip state=latest

- name: Add apt key
  apt_key:
      keyserver: "hkp://p80.pool.sks-keyservers.net:80"
      id: "58118E89F3A912897C070ADBF76221572C52609D"

- name: Add source list
  apt_repository:
      repo: "deb https://apt.dockerproject.org/repo ubuntu-xenial main"


- name: Install docker
  apt: name=docker-engine

- name: Install docker-py
  pip: name=docker-py

- name: Start docker
  service: name=docker state=started
